### ISSUE TITLE
Resurrection Remix 5.8.5

### ISSUE THREAD

**Issue by Ingvarr71** [seluce/nougat_platform_manifest#1]
When building Resurrection Remix 5.8.5, errors occur:

ERROR: /home/iodine71/rr/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1119: The method update(SQLiteDatabase, ContentValues, String, String[]) is undefined for the type SQLiteQueryBuilder
ERROR: /home/iodine71/rr/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1298: The method delete(SQLiteDatabase, String, String[]) is undefined for the type SQLiteQueryBuilder
ERROR: /home/iodine71/rr/packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadStorageProvider.java:326: The method setFilterByString(String) is undefined for the type DownloadManager.Query
build/core/java.mk:730: ошибка выполнения рецепта для цели «/home/iodine71/rr/out/target/common/obj/APPS/DownloadProvider_intermediates/with-local/classes.dex»
make: *** [/home/iodine71/rr/out/target/common/obj/APPS/DownloadProvider_intermediates/with-local/classes.dex] Ошибка 41
make: *** Ожидание завершения заданий…
make: выход из каталога «/home/iodine71/rr»

**Comment by seluce** [comment]
Hi, check readme please: https://github.com/seluce/nougat_platform_manifest#resurrection-remix-585-reborn

You need to sync first the manifest and after that you need to run n_asb script

You need both. Otherweise some patches are missing and you run into this error


https://github.com/seluce/n_asb


Step 1: sync reborn manifest
Step 2: sync n_asb and apply patches
Step 3: compile it again
