### ISSUE TITLE
DotOS

### ISSUE THREAD

**Issue by Ingvarr71** [seluce/nougat_platform_manifest#2]
Hello!
I get a build error:

Generate: system/core/rootdir/init.environ.rc.in -> /home/iodine71/dotos/out/target/product/a610/obj/ETC/init.environ.rc_intermediates/init.environ.rc
Install: /home/iodine71/dotos/out/target/product/a610/root/init.rc
Install: /home/iodine71/dotos/out/target/product/a610/root/res/images/charger/battery_fail.png
/bin/bash: -c: строка 0: неожиданный EOF при поиске соответствующего `''
/bin/bash: -c: строка 1: ошибка синтаксиса: неожиданный конец файла
system/core/rootdir/Android.mk:165: ошибка выполнения рецепта для цели «/home/iodine71/dotos/out/target/product/a610/obj/ETC/init.environ.rc_intermediates/init.environ.rc»
make: *** [/home/iodine71/dotos/out/target/product/a610/obj/ETC/init.environ.rc_intermediates/init.environ.rc] Ошибка 1
make: *** Ожидание завершения заданий…
make: выход из каталога «/home/iodine71/dotos»

**Comment by seluce** [comment]
Hi,

actually i don't know why you get this error. 
It's working fine for me with MT6737T (3.18.35) and MT6580 (3.18.19)

Did you applied n_asb patches after repo sync? But it seems this error depends on your device tree and not the source code. You applied the device patches as well, right?

I could help more if the source code would be in english :P It's hard to read it with google translate.

**Comment by Ingvarr71** [comment]
n_asb patches applied. error at the beginning of assembly

**Comment by Ingvarr71** [comment]
/ bin / bash: -c: line 0: unexpected EOF while looking for the matching `` ''
/ bin / bash: -c: line 1: syntax error: unexpected end of file
system / core / rootdir / Android.mk: 165: error executing the recipe for the target "/home/iodine71/dotos/out/target/product/a610/obj/ETC/init.environ.rc_intermediates/init.environ.rc"

**Comment by seluce** [comment]
Ah.. i guess it depends on your linix environment. 
Seems a bug between your linux and the source code of DotOS / LineageOS.

the compiler has issues to find the matching of " or '

Try this:
Go to: system / core / rootdir / Android.mk

Find this line: @echo "Generate: $< -> $@"
and replace it with: @echo 'Generate: $< -> $@'

**Comment by Ingvarr71** [comment]
28.04.18, 01:38
http://4pda.ru/forum/index.php?s=&showtopic=884459&view=findpost&p=72824443

**Comment by Ingvarr71** [comment]
Install: /home/iodine71/dotos/out/target/product/a610/root/res/images/charger/battery_scale.png
/ bin / bash: -c: line 0: unexpected EOF while looking for the matching `` ''
Install: /home/iodine71/dotos/out/target/product/a610/root/res/images/charger/cm_battery_scale.png
/ bin / bash: -c: line 1: syntax error: unexpected end of file
system / core / rootdir / Android.mk: 165: error executing the recipe for the target "/home/iodine71/dotos/out/target/product/a610/obj/ETC/init.environ.rc_intermediates/init.environ.rc"

**Comment by Ingvarr71** [comment]
I'll try to download the source again

**Comment by seluce** [comment]
Maybe try first my way and replace the syntax. But it's strange because the other ROMs (RR, CrDroid) have exactly the same syntax / file. No clue why it doesn't work for you.
I would prefer to redownload and restart your computer before you compile.

**Comment by Ingvarr71** [comment]
RR and CrDroid I collected. And on DotOS an error

**Comment by seluce** [comment]
You tried to rename the syntax like i wrote above?
(it's strange because the files are 1:1 the same like in RR or CrDroid) 

Its fine on my device with different device trees. Another Dev will try it later and check if it's work for him too (mt6753 3.18.19)

**Comment by Ingvarr71** [comment]
I turned off the init.environ.rc build, the error went away and the firmware was compiled. Then I replaced the assembled boot.img with boot.img from the DotOS firmware that I compiled earlier. The firmware has booted and everything works.

**Comment by seluce** [comment]
Sounds good.
Mt6753 64bit 3.18.19 device tree has no issues on dotos (h0sch tried it as well)
